name: paris_weather
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  freezed: ^2.4.7
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  bloc_test: ^9.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1  
  flutter_lints: ^3.0.0
  mockito: ^5.4.4

flutter:

  uses-material-design: true
