name: paris_weather
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc_test: ^9.1.7
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  equatable: ^2.0.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  retrofit: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.7.1  
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  retrofit_generator: ^7.0.8

flutter:

  uses-material-design: true
