// Mocks generated by Mockito 5.4.4 from annotations
// in paris_weather/test/weather_list/cubit/weather_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:paris_weather/core/network/apis_helper.dart' as _i4;
import 'package:paris_weather/weather_list/bloc/weather_list_cubit.dart' as _i6;
import 'package:paris_weather/weather_list/bloc/weather_list_state.dart' as _i3;
import 'package:paris_weather/weather_list/models/weather_response.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherResponse_0 extends _i1.SmartFake
    implements _i2.WeatherResponse {
  _FakeWeatherResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherListState_1 extends _i1.SmartFake
    implements _i3.WeatherListState {
  _FakeWeatherListState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApisHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockApisHelper extends _i1.Mock implements _i4.ApisHelper {
  MockApisHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.WeatherResponse> getWeatherData(
    String? query,
    String? appid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherData,
          [
            query,
            appid,
          ],
        ),
        returnValue:
            _i5.Future<_i2.WeatherResponse>.value(_FakeWeatherResponse_0(
          this,
          Invocation.method(
            #getWeatherData,
            [
              query,
              appid,
            ],
          ),
        )),
      ) as _i5.Future<_i2.WeatherResponse>);
}

/// A class which mocks [WeatherListCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherListCubit extends _i1.Mock implements _i6.WeatherListCubit {
  @override
  _i3.WeatherListState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeWeatherListState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeWeatherListState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.WeatherListState);

  @override
  _i5.Stream<_i3.WeatherListState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.WeatherListState>.empty(),
        returnValueForMissingStub: _i5.Stream<_i3.WeatherListState>.empty(),
      ) as _i5.Stream<_i3.WeatherListState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void getWeatherData({
    required String? city,
    required String? appId,
    required _i4.ApisHelper? apisHelper,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #getWeatherData,
          [],
          {
            #city: city,
            #appId: appId,
            #apisHelper: apisHelper,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.WeatherListState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i7.Change<_i3.WeatherListState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
